version: '2'
services: 
  db:
    image: mysql:5.5
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: acuDb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
  apache: 
    build: .
    ports:
      - "8001:80"
    volumes:
      - ./app:/var/www/html
    links:
      - db
    privileged: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
